build_pdf:
	# pandoc proposal.md -f markdown --latex-engine=xelatex --filter pandoc-citeproc \
	#  --bibliography=proposal.bib --template=../template.tex -o proposal.pdf \
	#  --variable colorlinks --toc --variable toc-own-page


		pandoc equivalence.md -f markdown --template=../../../template.tex -o equivalence.pdf
