build_html:
	pandoc exploration.md -f markdown --pdf-engine=xelatex --template=../../template.tex -o exploration.pdf
	pandoc representation.md -f markdown --pdf-engine=xelatex --template=../../template.tex -o representation.pdf
