build_html:
	# pandoc lmdp-derivations.md -f markdown --pdf-engine=xelatex --template=../../template.tex -o lmdp-derivations.pdf
	# pandoc lmdp-optimality.md -f markdown --pdf-engine=xelatex --template=../../template.tex -o lmdp-optimality.pdf
	pandoc lmdp-images.md -f markdown --pdf-engine=xelatex --template=../../template.tex -o lmdp-images.pdf
