build_html:
	pandoc -f markdown -t html5 --standalone -o ../docs/requests.html -c ../style.css -H ../docs/mathjax-header.html --mathjax=../docs/mathjax.js requests-for-research.md
	pandoc -f markdown -t html5 --standalone -o ../docs/summaries.html -c ../style.css -H ../docs/mathjax-header.html --mathjax=../docs/mathjax.js summaries.md
