build_html:
	pandoc near-optimal-representation.md -f markdown --pdf-engine=xelatex --template=../template.tex -o near-optimal-representation.pdf
	pandoc linear-gpi.md -f markdown --pdf-engine=xelatex --template=../template.tex -o linear-gpi.pdf
	pandoc actions.md -f markdown --pdf-engine=xelatex --template=../template.tex -o actions.pdf
	pandoc disentangled-symmetry.md -f markdown --pdf-engine=xelatex --template=../template.tex -o disentangled-symmetry.pdf
