build_html:
	pandoc polytope.md -f markdown --pdf-engine=xelatex --template=../template.tex -o polytope.pdf
	pandoc representation.md -f markdown --pdf-engine=xelatex --template=../template.tex -o representation.pdf
